language: python
python:
  - "3.6"
  - "3.7"

install:
  - pip install coveralls
  - pip install -r requirements.txt

script:
    - nosetests -w snare/tests -vv --with-coverage --cover-inclusive --cover-package=snare
    - pycodestyle . --max-line-length=120

after_success:
  - coveralls
